version: '3.5'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: gym_app
      POSTGRES_DB: gym_app_db
      POSTGRES_PASSWORD: password
    volumes:
       - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped