# Generated by Django 4.1.4 on 2022-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('url', models.CharField(db_index=True, max_length=256, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
