# Generated by Django 4.1.4 on 2022-12-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript_json',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_text',
            field=models.TextField(null=True),
        ),
    ]
