# Generated by Django 4.1.4 on 2022-12-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_video_transcript_json_video_transcript_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='openapi_prompt_template',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='openapi_response',
            field=models.JSONField(null=True),
        ),
    ]
