# Generated by Django 4.1.4 on 2022-12-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_video_openapi_prompt_template_video_openapi_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToExercisesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField()),
                ('openapi_prompt_template', models.TextField()),
                ('openapi_response', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='openapi_prompt_template',
        ),
        migrations.RemoveField(
            model_name='video',
            name='openapi_response',
        ),
    ]
