# Generated by Django 4.1.4 on 2022-12-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_texttoexercisesresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttoexercisesresult',
            name='transcript_text',
            field=models.TextField(db_index=True),
        ),
    ]
