# Generated by Django 4.1.4 on 2022-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_alter_texttoexercisesresult_transcript_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='exercises',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='texttoexercisesresult',
            name='openapi_prompt_template',
            field=models.TextField(db_index=True),
        ),
    ]
