# Generated by Django 4.1.4 on 2022-12-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_video_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='exercises',
        ),
        migrations.AddField(
            model_name='texttoexercisesresult',
            name='exercises',
            field=models.JSONField(null=True),
        ),
    ]
