# Generated by Django 4.1.4 on 2022-12-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_remove_video_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttoexercisesresult',
            name='succeed_to_parse',
            field=models.BooleanField(null=True),
        ),
    ]
