# Generated by Django 4.1.4 on 2022-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0010_alter_texttoexercisesresult_openapi_prompt_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='training_logs/')),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
