# Generated by Django 4.1.4 on 2022-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0011_traininglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglog',
            name='ket',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
    ]
