# Generated by Django 4.1.4 on 2022-12-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0012_traininglog_ket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininglog',
            old_name='text',
            new_name='transcript_text',
        ),
        migrations.AddField(
            model_name='traininglog',
            name='transcript_json',
            field=models.JSONField(null=True),
        ),
    ]
