# Generated by Django 4.1.4 on 2022-12-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0013_rename_text_traininglog_transcript_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininglog',
            old_name='ket',
            new_name='key',
        ),
    ]
