# Generated by Django 4.1.4 on 2022-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0014_rename_ket_traininglog_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField()),
                ('openapi_prompt_template', models.TextField()),
                ('openapi_response', models.JSONField()),
                ('succeed_to_parse', models.BooleanField(null=True)),
                ('training_log', models.JSONField(null=True)),
            ],
        ),
    ]
