# Generated by Django 4.1.4 on 2022-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0015_texttotraininglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration_s',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_metadata',
            field=models.JSONField(null=True),
        ),
    ]
