# Generated by Django 4.1.4 on 2022-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0016_video_duration_s_video_title_video_youtube_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttoexercisesresult',
            name='transcript_length_in_token',
            field=models.IntegerField(null=True),
        ),
    ]
