# Generated by Django 4.1.4 on 2022-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0018_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_or_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
