# Generated by Django 4.1.4 on 2022-12-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0019_subscriber_is_or_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
